config/routes.rb
MusicAnywhere::Application.routes.draw do
	match '/login', :to => 'pages#login'
	match '/about', :to => 'pages#about'
	match '/signup', :to => 'pages#signup'
	root :to => 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Home"
  end

  def login
	@title = "Login"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Music Anywhere"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>  <nav class="round">    <ul>      <li><%= link_to "About", about_path %></li>      <li><%= link_to "Contact", contact_path %></li>          </ul>  </nav></footer>

app/views/layouts/_header.html.erb
<header>  <% logo = image_tag("logo.png", :alt => "Music Anywhere", :class => "round") %>  <%= link_to logo, root_path %>  <nav class="round">    <ul>      <li><%= link_to "Home", root_path %></li>      <li><%= link_to "Help", help_path %></li>      <li><%= link_to "Sign in", 'login_path' %></li>    </ul>  </nav></header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>
	<div class="container">
      <header>
        <%= image_tag("logo.png", :alt => "Music Anywhere", :class => "round") %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>            
            <li><%= link_to "Sign in", login_path %></li>
          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to Music Anywhere!</h1>
<p>New here? Why don't you </p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/pages/login.html.erb
<h1>Pages#login</h1>
<p>Find me in app/views/pages/login.html.erb</p>

app/views/pages/signup.html.erb
<h1>Pages#signup</h1>
<p>Find me in app/views/pages/signup.html.erb</p>